### ISSUE TITLE
How to add it to cmake project?

### ISSUE THREAD

**Issue by lihao2333** [jbehley/octree#12]
I want to use it in my cmake project.  I should add some line to my `CMakeLists.txt` like follows. 
```
find_package(xxx)
include_directories(${xxxx})
target_link_libraries(${xxx})
```
What the xxx for this repo? Thanks!

**Comment by jbehley** [comment]
Hi @lihao2333,

I would recommend just copying and including the `octree.hpp`. That's all you need to get it running. See also the examples to get an idea.

I don't explicitly made a "cmake-able" project out of it.

**Comment by jbehley** [comment]
It seems not an issue anymore. Therefore I close this.

If you still have a problem, please re-open this issue.
