### ISSUE TITLE
can colour be in point attribute? 

### ISSUE THREAD

**Issue by zuixiaosanlang** [jbehley/octree#16]
now, i only found point(x, y, z),  not include point-cloud other attribute, example color(r,g,b), (nx,ny,nz)

how to add other attribute?
thanks

**Comment by jbehley** [comment]
Have a look at the second example: https://github.com/jbehley/octree/blob/master/examples/example2.cpp

You can have an arbitrary point and just have to provide accessors for x,y,z as this is used to build the octree. if the point has additional data that doesn't matter for the octree as long as it has accessors for the coordinates.
